### ISSUE TITLE
Would be very useful but ain't working for me

### ISSUE THREAD

**Issue by j3k0** [yllus/status-page-for-runscope#1]
Hello,

I installed by creating a zip of the git repo, then followed the instruction: bucket key, auth token, etc.

Here's the error I see in the browser console when opening the page:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
https://fovea.cc/wp-admin/admin-ajax.php?action=runscope_display_test_results&post_id=403
```

You can check by yourself here: https://fovea.cc/blog/index.php/triominos-server-status/

Thanks for plugin, would definitely use it if's working!

**Comment by yllus** [comment]
I believe https://github.com/yllus/runscope-status-page-wp-plugin/commit/3c13a89e69487f52f2b31d85c186935b4f96b0f0 should address this issue; can you pull the latest version of the plug-in and give it another try?

**Comment by j3k0** [comment]
I fixed it using wordpress's `admin_url()` function. See https://github.com/j3k0/runscope-status-page-wp-plugin/commit/b0dfa25f5cbd4f74d60b5d28903c76accfb3226b

It's working for me this way.

Will make a pull request if you find it cleaner, fill free to reject if not.
